// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { TestCommand } from './test-command.js'

// Pass to the bus with Bus.configure().withMessageTypes(messageTypes)
export const messageTypes: MessageTypes = {
  source: '@node-ts/bus-azure-service-bus/src/test/message-types.generated',
  messages: {
    '@node-ts/bus-azure-service-bus/test-command':
      '@node-ts/bus-azure-service-bus/src/test/test-command#TestCommand'
  },
  types: {
    '@node-ts/bus-azure-service-bus/src/test/test-command#TestCommand': {
      class: TestCommand,
      fields: {}
    }
  }
}
