// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { TracedCommand } from './traced-command.js'
import { TracedEvent } from './traced-event.js'

// Pass to the bus with Bus.configure().withMessageTypes(messageTypes)
export const messageTypes: MessageTypes = {
  source: '@node-ts/bus-opentelemetry/src/test/message-types.generated',
  messages: {
    '@node-ts/bus-opentelemetry/traced-command':
      '@node-ts/bus-opentelemetry/src/test/traced-command#TracedCommand',
    '@node-ts/bus-opentelemetry/traced-event':
      '@node-ts/bus-opentelemetry/src/test/traced-event#TracedEvent'
  },
  types: {
    '@node-ts/bus-opentelemetry/src/test/traced-command#TracedCommand': {
      class: TracedCommand,
      fields: {}
    },
    '@node-ts/bus-opentelemetry/src/test/traced-event#TracedEvent': {
      class: TracedEvent,
      fields: {}
    }
  }
}
