import { dirname, relative } from 'node:path'
import { FieldModel, MessageTypesModel } from './message-types-model'

/**
 * The first line of every generated file
 */
export const GENERATED_HEADER =
  "// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand."

/**
 * How relative imports in the generated file end
 */
export type ImportExtension = 'js' | 'none'

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/

const quote = (value: string): string =>
  `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`

const propertyKey = (key: string): string =>
  IDENTIFIER.test(key) ? key : quote(key)

const writeFieldType = (fieldType: FieldModel | 'plain'): string => {
  if (typeof fieldType === 'string') {
    return quote(fieldType)
  }
  if ('type' in fieldType) {
    return `{ type: ${quote(fieldType.type)} }`
  }
  if ('array' in fieldType) {
    return `{ array: ${writeFieldType(fieldType.array)} }`
  }
  if ('set' in fieldType) {
    return `{ set: ${writeFieldType(fieldType.set)} }`
  }
  if ('map' in fieldType) {
    const keys = fieldType.keys ? `, keys: ${quote(fieldType.keys)}` : ''
    return `{ map: ${writeFieldType(fieldType.map)}${keys} }`
  }
  return `{ record: ${writeFieldType(fieldType.record)} }`
}

const importPath = (
  fromFile: string,
  toFile: string,
  importExtension: ImportExtension
): string => {
  const withoutExtension = relative(dirname(fromFile), toFile)
    .split('\\')
    .join('/')
    .replace(/\.(d\.)?([mc]?)tsx?$/, (_, __, kind: string) =>
      importExtension === 'js' ? `.${kind}js` : ''
    )
  return withoutExtension.startsWith('.')
    ? withoutExtension
    : `./${withoutExtension}`
}

/**
 * Writes the source of the generated file
 * @param model the message types to write
 * @param outFile the absolute path the file is written to, which imports are relative to
 * @param importExtension how relative imports end, which depends on the project's module resolution
 * @returns the TypeScript source of the generated file
 */
export const writeMessageTypes = (
  model: MessageTypesModel,
  outFile: string,
  importExtension: ImportExtension
): string => {
  const importsByPath = new Map<string, string[]>()
  for (const { key, class: classModel } of model.types) {
    if (!classModel) {
      continue
    }
    const path = importPath(outFile, classModel.fileName, importExtension)
    const specifier =
      classModel.exportName === key ? key : `${classModel.exportName} as ${key}`
    importsByPath.set(path, [...(importsByPath.get(path) ?? []), specifier])
  }

  const lines = [
    GENERATED_HEADER,
    "import type { MessageTypes } from '@node-ts/bus-messages'"
  ]
  for (const path of [...importsByPath.keys()].sort()) {
    const specifiers = importsByPath.get(path)!.sort()
    lines.push(`import { ${specifiers.join(', ')} } from ${quote(path)}`)
  }

  lines.push('', 'export const messageTypes: MessageTypes = {', '  messages: {')
  model.messages.forEach(([name, typeKey], index) => {
    const comma = index < model.messages.length - 1 ? ',' : ''
    lines.push(`    ${propertyKey(name)}: ${quote(typeKey)}${comma}`)
  })
  lines.push('  },', '  types: {')
  model.types.forEach((typeModel, typeIndex) => {
    lines.push(`    ${propertyKey(typeModel.key)}: {`)
    if (typeModel.class) {
      lines.push(`      class: ${typeModel.key},`)
    }
    if (typeModel.fields.length) {
      lines.push('      fields: {')
      typeModel.fields.forEach(([field, fieldType], fieldIndex) => {
        const comma = fieldIndex < typeModel.fields.length - 1 ? ',' : ''
        lines.push(
          `        ${propertyKey(field)}: ${writeFieldType(fieldType)}${comma}`
        )
      })
      lines.push('      }')
    } else {
      lines.push('      fields: {}')
    }
    lines.push(typeIndex < model.types.length - 1 ? '    },' : '    }')
  })
  lines.push('  }', '}', '')
  return lines.join('\n')
}
