import { MessageTypes } from '@node-ts/bus-messages'
import { ClassConstructor } from '../util'
import { MessageTypeReviver } from './message-type-reviver'
import { Serializer } from './serializer'

/**
 * Writes the values JSON can't represent as plain JSON: a Map as an object of its entries, a Set
 * as an array and a bigint as a string. Dates already become ISO strings through `toJSON`.
 */
const toJsonValue = (_: string, value: unknown): unknown => {
  if (typeof value === 'bigint') {
    return value.toString()
  }
  if (value instanceof Map) {
    return Object.fromEntries(value)
  }
  if (value instanceof Set) {
    return [...value]
  }
  return value
}

const NO_MESSAGE_TYPES: MessageTypes = Object.freeze({
  messages: Object.freeze({}),
  types: Object.freeze({})
})

/**
 * The default serializer. Messages and workflow state are written as plain JSON, with Maps as
 * objects, Sets as arrays and bigints as strings, so nothing is added to the payload.
 *
 * When reading, the top-level object is created from its class' prototype, without running its
 * constructor. Dates, Maps, Sets, bigints and class instances are restored at any depth using the message
 * types the reading bus passes, which are the files generated by `bus generate-message-types` (in
 * `@node-ts/bus-cli`) given to `withMessageTypes()`. Nested values of other messages stay as JSON parsed
 * them, e.g. Dates stay ISO strings.
 *
 * It holds no state, so one instance can be shared by several buses.
 */
export class JsonSerializer implements Serializer {
  private readonly reviver = new MessageTypeReviver()

  serialize<ObjectType extends object>(obj: ObjectType): string {
    return JSON.stringify(obj, toJsonValue)
  }

  deserialize<ObjectType extends object>(
    serialized: string,
    classConstructor: ClassConstructor<ObjectType>,
    messageTypes?: MessageTypes
  ): ObjectType {
    const plain = JSON.parse(serialized) as object
    return this.toClass(plain, classConstructor, messageTypes)
  }

  toPlain<T extends object>(obj: T): object {
    return JSON.parse(this.serialize(obj)) as object
  }

  toClass<T extends object>(
    obj: object,
    classConstructor: ClassConstructor<T>,
    messageTypes: MessageTypes = NO_MESSAGE_TYPES
  ): T {
    return this.reviver.revive<T>(
      obj,
      classConstructor.prototype as object,
      messageTypes
    )
  }
}
