// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { TestCommand } from './test-command.js'
import { UnhandledCommand } from './unhandled-command.js'

// Pass to the bus with Bus.configure().withMessageTypes(messageTypes)
export const messageTypes: MessageTypes = {
  source: '@node-ts/bus-sqs-lambda/src/test/message-types.generated',
  messages: {
    '@node-ts/bus-sqs-lambda/test-command':
      '@node-ts/bus-sqs-lambda/src/test/test-command#TestCommand',
    '@node-ts/bus-sqs-lambda/unhandled-command':
      '@node-ts/bus-sqs-lambda/src/test/unhandled-command#UnhandledCommand'
  },
  types: {
    '@node-ts/bus-sqs-lambda/src/test/test-command#TestCommand': {
      class: TestCommand,
      fields: {}
    },
    '@node-ts/bus-sqs-lambda/src/test/unhandled-command#UnhandledCommand': {
      class: UnhandledCommand,
      fields: {}
    }
  }
}
