// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { ChargeCreditCard } from './messages/charge-credit-card'
import { CreditCardCharged } from './messages/credit-card-charged'
import {
  DocumentRead,
  DocumentUploaded,
  ReadDocument
} from './messages/documents'
import {
  EmailReceipt,
  ItemPurchased,
  ItemShipped,
  ReceiptEmailed,
  ShipItem
} from './messages/fulfilment'
import { ReserveRoom, RoomReserved } from './messages/reserve-room'
import {
  EncodeVideo,
  VideoEncoded,
  VideoEncodingStarted
} from './messages/videos'
import { DocumentWorkflowState } from './workflows/document-workflow-state'
import { FulfilmentWorkflowState } from './workflows/fulfilment-workflow-state'

// Pass to the bus with Bus.configure().withMessageTypes(messageTypes)
export const messageTypes: MessageTypes = {
  source: 'bus-docs/snippets/message-types.generated',
  messages: {
    'my-app/accounts/charge-credit-card':
      'bus-docs/snippets/messages/charge-credit-card#ChargeCreditCard',
    'my-app/accounts/credit-card-charged':
      'bus-docs/snippets/messages/credit-card-charged#CreditCardCharged',
    'my-app/accounts/payment-refunded':
      'bus-docs/snippets/messages-without-a-class#PaymentRefunded',
    'my-app/accounts/refund-payment':
      'bus-docs/snippets/messages-without-a-class#RefundPayment',
    'my-app/documents/document-read':
      'bus-docs/snippets/messages/documents#DocumentRead',
    'my-app/documents/document-uploaded':
      'bus-docs/snippets/messages/documents#DocumentUploaded',
    'my-app/documents/document-workflow-state':
      'bus-docs/snippets/workflows/document-workflow-state#DocumentWorkflowState',
    'my-app/documents/read-document':
      'bus-docs/snippets/messages/documents#ReadDocument',
    'my-app/email/email-receipt':
      'bus-docs/snippets/messages/fulfilment#EmailReceipt',
    'my-app/email/receipt-emailed':
      'bus-docs/snippets/messages/fulfilment#ReceiptEmailed',
    'my-app/shipping/item-shipped':
      'bus-docs/snippets/messages/fulfilment#ItemShipped',
    'my-app/shipping/ship-item':
      'bus-docs/snippets/messages/fulfilment#ShipItem',
    'my-app/store/fulfilment-workflow-state':
      'bus-docs/snippets/workflows/fulfilment-workflow-state#FulfilmentWorkflowState',
    'my-app/store/item-purchased':
      'bus-docs/snippets/messages/fulfilment#ItemPurchased',
    'my-app/videos/encode-video':
      'bus-docs/snippets/messages/videos#EncodeVideo',
    'my-app/videos/video-encoded':
      'bus-docs/snippets/messages/videos#VideoEncoded',
    'my-app/videos/video-encoding-started':
      'bus-docs/snippets/messages/videos#VideoEncodingStarted',
    'reservations/reserve-room':
      'bus-docs/snippets/messages/reserve-room#ReserveRoom',
    'reservations/room-reserved':
      'bus-docs/snippets/messages/reserve-room#RoomReserved'
  },
  types: {
    'bus-docs/snippets/messages-without-a-class#PaymentRefunded': {
      fields: {}
    },
    'bus-docs/snippets/messages-without-a-class#RefundPayment': {
      fields: {
        refundedAt: 'Date'
      }
    },
    'bus-docs/snippets/messages/charge-credit-card#ChargeCreditCard': {
      class: ChargeCreditCard,
      fields: {}
    },
    'bus-docs/snippets/messages/credit-card-charged#CreditCardCharged': {
      class: CreditCardCharged,
      fields: {
        chargedAt: 'Date'
      }
    },
    'bus-docs/snippets/messages/documents#DocumentRead': {
      class: DocumentRead,
      fields: {}
    },
    'bus-docs/snippets/messages/documents#DocumentUploaded': {
      class: DocumentUploaded,
      fields: {}
    },
    'bus-docs/snippets/messages/documents#ReadDocument': {
      class: ReadDocument,
      fields: {}
    },
    'bus-docs/snippets/messages/fulfilment#EmailReceipt': {
      class: EmailReceipt,
      fields: {}
    },
    'bus-docs/snippets/messages/fulfilment#ItemPurchased': {
      class: ItemPurchased,
      fields: {}
    },
    'bus-docs/snippets/messages/fulfilment#ItemShipped': {
      class: ItemShipped,
      fields: {
        shippedAt: 'Date'
      }
    },
    'bus-docs/snippets/messages/fulfilment#ReceiptEmailed': {
      class: ReceiptEmailed,
      fields: {}
    },
    'bus-docs/snippets/messages/fulfilment#ShipItem': {
      class: ShipItem,
      fields: {}
    },
    'bus-docs/snippets/messages/reserve-room#ReserveRoom': {
      class: ReserveRoom,
      fields: {}
    },
    'bus-docs/snippets/messages/reserve-room#RoomReserved': {
      class: RoomReserved,
      fields: {}
    },
    'bus-docs/snippets/messages/videos#EncodeVideo': {
      class: EncodeVideo,
      fields: {}
    },
    'bus-docs/snippets/messages/videos#VideoEncoded': {
      class: VideoEncoded,
      fields: {}
    },
    'bus-docs/snippets/messages/videos#VideoEncodingStarted': {
      class: VideoEncodingStarted,
      fields: {}
    },
    'bus-docs/snippets/workflows/document-workflow-state#DocumentWorkflowState':
      {
        class: DocumentWorkflowState,
        fields: {}
      },
    'bus-docs/snippets/workflows/fulfilment-workflow-state#FulfilmentWorkflowState':
      {
        class: FulfilmentWorkflowState,
        fields: {
          shippedAt: 'Date'
        }
      }
  }
}
