// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { ChargeCreditCard } from './messages/charge-credit-card'
import {
  CheckCredit,
  CreditCheckTimedOut,
  CreditChecked,
  OrderSubmitted
} from './messages/credit'
import { CreditCardCharged } from './messages/credit-card-charged'
import {
  DocumentRead,
  DocumentUploaded,
  ReadDocument
} from './messages/documents'
import {
  EmailReceipt,
  ItemPurchased,
  ItemShipped,
  ReceiptEmailed,
  ShipItem
} from './messages/fulfilment'
import {
  CancelOrder,
  OrderPlaced,
  OrderShipped,
  PaymentReceived,
  PaymentTimedOut,
  ShipOrder
} from './messages/payment'
import { ReserveRoom, RoomReserved } from './messages/reserve-room'
import {
  EncodeVideo,
  VideoEncoded,
  VideoEncodingStarted
} from './messages/videos'
import { CreditCheckState } from './workflows/credit-check-state'
import { DocumentWorkflowState } from './workflows/document-workflow-state'
import { FulfilmentWorkflowState } from './workflows/fulfilment-workflow-state'
import { OrderApprovalState } from './workflows/order-approval-state'
import { OrderPaymentState } from './workflows/order-payment-state'

// Pass to the bus with Bus.configure().withMessageTypes(messageTypes)
export const messageTypes: MessageTypes = {
  source: 'bus-docs/snippets/message-types.generated',
  messages: {
    'my-app/accounts/charge-credit-card':
      'bus-docs/snippets/messages/charge-credit-card#ChargeCreditCard',
    'my-app/accounts/credit-card-charged':
      'bus-docs/snippets/messages/credit-card-charged#CreditCardCharged',
    'my-app/accounts/payment-refunded':
      'bus-docs/snippets/messages-without-a-class#PaymentRefunded',
    'my-app/accounts/refund-payment':
      'bus-docs/snippets/messages-without-a-class#RefundPayment',
    'my-app/credit/check-credit':
      'bus-docs/snippets/messages/credit#CheckCredit',
    'my-app/credit/credit-check-state':
      'bus-docs/snippets/workflows/credit-check-state#CreditCheckState',
    'my-app/credit/credit-checked':
      'bus-docs/snippets/messages/credit#CreditChecked',
    'my-app/documents/document-read':
      'bus-docs/snippets/messages/documents#DocumentRead',
    'my-app/documents/document-uploaded':
      'bus-docs/snippets/messages/documents#DocumentUploaded',
    'my-app/documents/document-workflow-state':
      'bus-docs/snippets/workflows/document-workflow-state#DocumentWorkflowState',
    'my-app/documents/read-document':
      'bus-docs/snippets/messages/documents#ReadDocument',
    'my-app/email/email-receipt':
      'bus-docs/snippets/messages/fulfilment#EmailReceipt',
    'my-app/email/receipt-emailed':
      'bus-docs/snippets/messages/fulfilment#ReceiptEmailed',
    'my-app/orders/cancel-order':
      'bus-docs/snippets/messages/payment#CancelOrder',
    'my-app/orders/credit-check-timed-out':
      'bus-docs/snippets/messages/credit#CreditCheckTimedOut',
    'my-app/orders/order-approval-state':
      'bus-docs/snippets/workflows/order-approval-state#OrderApprovalState',
    'my-app/orders/order-payment-state':
      'bus-docs/snippets/workflows/order-payment-state#OrderPaymentState',
    'my-app/orders/order-placed':
      'bus-docs/snippets/messages/payment#OrderPlaced',
    'my-app/orders/order-submitted':
      'bus-docs/snippets/messages/credit#OrderSubmitted',
    'my-app/orders/payment-timed-out':
      'bus-docs/snippets/messages/payment#PaymentTimedOut',
    'my-app/payments/payment-received':
      'bus-docs/snippets/messages/payment#PaymentReceived',
    'my-app/shipping/item-shipped':
      'bus-docs/snippets/messages/fulfilment#ItemShipped',
    'my-app/shipping/order-shipped':
      'bus-docs/snippets/messages/payment#OrderShipped',
    'my-app/shipping/ship-item':
      'bus-docs/snippets/messages/fulfilment#ShipItem',
    'my-app/shipping/ship-order':
      'bus-docs/snippets/messages/payment#ShipOrder',
    'my-app/store/fulfilment-workflow-state':
      'bus-docs/snippets/workflows/fulfilment-workflow-state#FulfilmentWorkflowState',
    'my-app/store/item-purchased':
      'bus-docs/snippets/messages/fulfilment#ItemPurchased',
    'my-app/videos/encode-video':
      'bus-docs/snippets/messages/videos#EncodeVideo',
    'my-app/videos/video-encoded':
      'bus-docs/snippets/messages/videos#VideoEncoded',
    'my-app/videos/video-encoding-started':
      'bus-docs/snippets/messages/videos#VideoEncodingStarted',
    'reservations/reserve-room':
      'bus-docs/snippets/messages/reserve-room#ReserveRoom',
    'reservations/room-reserved':
      'bus-docs/snippets/messages/reserve-room#RoomReserved'
  },
  types: {
    'bus-docs/snippets/messages-without-a-class#PaymentRefunded': {
      fields: {}
    },
    'bus-docs/snippets/messages-without-a-class#RefundPayment': {
      fields: {
        refundedAt: 'Date'
      }
    },
    'bus-docs/snippets/messages/charge-credit-card#ChargeCreditCard': {
      class: ChargeCreditCard,
      fields: {}
    },
    'bus-docs/snippets/messages/credit#CheckCredit': {
      class: CheckCredit,
      fields: {}
    },
    'bus-docs/snippets/messages/credit#CreditCheckTimedOut': {
      class: CreditCheckTimedOut,
      fields: {}
    },
    'bus-docs/snippets/messages/credit#CreditChecked': {
      class: CreditChecked,
      fields: {}
    },
    'bus-docs/snippets/messages/credit#OrderSubmitted': {
      class: OrderSubmitted,
      fields: {}
    },
    'bus-docs/snippets/messages/credit-card-charged#CreditCardCharged': {
      class: CreditCardCharged,
      fields: {
        chargedAt: 'Date'
      }
    },
    'bus-docs/snippets/messages/documents#DocumentRead': {
      class: DocumentRead,
      fields: {}
    },
    'bus-docs/snippets/messages/documents#DocumentUploaded': {
      class: DocumentUploaded,
      fields: {}
    },
    'bus-docs/snippets/messages/documents#ReadDocument': {
      class: ReadDocument,
      fields: {}
    },
    'bus-docs/snippets/messages/fulfilment#EmailReceipt': {
      class: EmailReceipt,
      fields: {}
    },
    'bus-docs/snippets/messages/fulfilment#ItemPurchased': {
      class: ItemPurchased,
      fields: {}
    },
    'bus-docs/snippets/messages/fulfilment#ItemShipped': {
      class: ItemShipped,
      fields: {
        shippedAt: 'Date'
      }
    },
    'bus-docs/snippets/messages/fulfilment#ReceiptEmailed': {
      class: ReceiptEmailed,
      fields: {}
    },
    'bus-docs/snippets/messages/fulfilment#ShipItem': {
      class: ShipItem,
      fields: {}
    },
    'bus-docs/snippets/messages/payment#CancelOrder': {
      class: CancelOrder,
      fields: {}
    },
    'bus-docs/snippets/messages/payment#OrderPlaced': {
      class: OrderPlaced,
      fields: {}
    },
    'bus-docs/snippets/messages/payment#OrderShipped': {
      class: OrderShipped,
      fields: {}
    },
    'bus-docs/snippets/messages/payment#PaymentReceived': {
      class: PaymentReceived,
      fields: {}
    },
    'bus-docs/snippets/messages/payment#PaymentTimedOut': {
      class: PaymentTimedOut,
      fields: {}
    },
    'bus-docs/snippets/messages/payment#ShipOrder': {
      class: ShipOrder,
      fields: {}
    },
    'bus-docs/snippets/messages/reserve-room#ReserveRoom': {
      class: ReserveRoom,
      fields: {}
    },
    'bus-docs/snippets/messages/reserve-room#RoomReserved': {
      class: RoomReserved,
      fields: {}
    },
    'bus-docs/snippets/messages/videos#EncodeVideo': {
      class: EncodeVideo,
      fields: {}
    },
    'bus-docs/snippets/messages/videos#VideoEncoded': {
      class: VideoEncoded,
      fields: {}
    },
    'bus-docs/snippets/messages/videos#VideoEncodingStarted': {
      class: VideoEncodingStarted,
      fields: {}
    },
    'bus-docs/snippets/workflows/credit-check-state#CreditCheckState': {
      class: CreditCheckState,
      fields: {}
    },
    'bus-docs/snippets/workflows/document-workflow-state#DocumentWorkflowState':
      {
        class: DocumentWorkflowState,
        fields: {}
      },
    'bus-docs/snippets/workflows/fulfilment-workflow-state#FulfilmentWorkflowState':
      {
        class: FulfilmentWorkflowState,
        fields: {
          shippedAt: 'Date'
        }
      },
    'bus-docs/snippets/workflows/order-approval-state#OrderApprovalState': {
      class: OrderApprovalState,
      fields: {}
    },
    'bus-docs/snippets/workflows/order-payment-state#OrderPaymentState': {
      class: OrderPaymentState,
      fields: {}
    }
  }
}
