import { MessageTypeReferenceNotFound, MessageTypesConflict } from './error'
import {
  MessageFieldType,
  MessageTypeDefinition,
  MessageTypes
} from './message-types'

const isSameDefinition = (
  a: MessageTypeDefinition,
  b: MessageTypeDefinition
): boolean =>
  a.class === b.class && JSON.stringify(a.fields) === JSON.stringify(b.fields)

const assertReferencesExist = (messageTypes: MessageTypes): void => {
  const assertExists = (typeKey: string, referencedFrom: string) => {
    if (!Object.hasOwn(messageTypes.types, typeKey)) {
      throw new MessageTypeReferenceNotFound(typeKey, referencedFrom)
    }
  }
  const assertFieldType = (
    fieldType: MessageFieldType | 'plain',
    referencedFrom: string
  ): void => {
    if (typeof fieldType === 'string') {
      return
    }
    if ('type' in fieldType) {
      assertExists(fieldType.type, referencedFrom)
    } else if ('array' in fieldType) {
      assertFieldType(fieldType.array, referencedFrom)
    } else if ('set' in fieldType) {
      assertFieldType(fieldType.set, referencedFrom)
    } else if ('map' in fieldType) {
      assertFieldType(fieldType.map, referencedFrom)
    } else {
      assertFieldType(fieldType.record, referencedFrom)
    }
  }

  for (const [name, typeKey] of Object.entries(messageTypes.messages)) {
    assertExists(typeKey, name)
  }
  for (const [typeKey, definition] of Object.entries(messageTypes.types)) {
    for (const [field, fieldType] of Object.entries(definition.fields)) {
      assertFieldType(fieldType, `${typeKey}.${field}`)
    }
  }
}

/**
 * Merges the message types of several message libraries into one, as the bus does with the message
 * types passed to `withMessageTypes()`. Nothing is shared between calls, so each bus has its own.
 *
 * Passing the same message types more than once is the same as passing them once.
 * @param messageTypes the message types to merge, usually the `messageTypes` export of each file
 * generated by `bus generate-message-types`
 * @returns the merged message types
 * @throws MessageTypeReferenceNotFound if some message types refer to a type they don't define
 * @throws MessageTypesConflict if two of them define a `$name` or type key differently
 * @example
 * import { messageTypes as orderMessageTypes } from '@my-org/order-messages'
 * import { messageTypes } from './message-types.generated'
 *
 * const merged = mergeMessageTypes([orderMessageTypes, messageTypes])
 */
export const mergeMessageTypes = (
  messageTypes: MessageTypes[]
): MessageTypes => {
  const merged: MessageTypes = { messages: {}, types: {} }
  const messageSources: { [$name: string]: string | undefined } = {}
  const typeSources: { [typeKey: string]: string | undefined } = {}
  for (const current of new Set(messageTypes)) {
    assertReferencesExist(current)
    for (const [name, typeKey] of Object.entries(current.messages)) {
      if (
        Object.hasOwn(merged.messages, name) &&
        merged.messages[name] !== typeKey
      ) {
        throw new MessageTypesConflict('$name', name, [
          messageSources[name],
          current.source
        ])
      }
      merged.messages[name] = typeKey
      messageSources[name] ??= current.source
    }
    for (const [typeKey, definition] of Object.entries(current.types)) {
      if (
        Object.hasOwn(merged.types, typeKey) &&
        !isSameDefinition(merged.types[typeKey], definition)
      ) {
        throw new MessageTypesConflict('type', typeKey, [
          typeSources[typeKey],
          current.source
        ])
      }
      merged.types[typeKey] = definition
      typeSources[typeKey] ??= current.source
    }
  }
  return merged
}
