import { MessageTypeReferenceNotFound, MessageTypesConflict } from './error'
import {
  MessageFieldType,
  MessageTypeDefinition,
  MessageTypes
} from './message-types'

/**
 * The registry lives on `globalThis` under a global symbol, so every copy of this package, and its
 * ES module and CommonJS entries, share it
 */
const REGISTRY_KEY = Symbol.for('@node-ts/bus/message-types')

interface MessageTypeRegistry {
  registrations: MessageTypes[]
  merged: MessageTypes
}

const getRegistry = (): MessageTypeRegistry => {
  const global = globalThis as { [REGISTRY_KEY]?: MessageTypeRegistry }
  global[REGISTRY_KEY] ??= {
    registrations: [],
    merged: { messages: {}, types: {} }
  }
  return global[REGISTRY_KEY]
}

const isSameDefinition = (
  a: MessageTypeDefinition,
  b: MessageTypeDefinition
): boolean =>
  a.class === b.class && JSON.stringify(a.fields) === JSON.stringify(b.fields)

const merge = (registrations: MessageTypes[]): MessageTypes => {
  const merged: MessageTypes = { messages: {}, types: {} }
  for (const messageTypes of registrations) {
    for (const [name, typeKey] of Object.entries(messageTypes.messages)) {
      if (
        Object.hasOwn(merged.messages, name) &&
        merged.messages[name] !== typeKey
      ) {
        throw new MessageTypesConflict('$name', name)
      }
      merged.messages[name] = typeKey
    }
    for (const [typeKey, definition] of Object.entries(messageTypes.types)) {
      if (
        Object.hasOwn(merged.types, typeKey) &&
        !isSameDefinition(merged.types[typeKey], definition)
      ) {
        throw new MessageTypesConflict('type', typeKey)
      }
      merged.types[typeKey] = definition
    }
  }
  return merged
}

const assertReferencesExist = (messageTypes: MessageTypes): void => {
  const assertExists = (typeKey: string, referencedFrom: string) => {
    if (!Object.hasOwn(messageTypes.types, typeKey)) {
      throw new MessageTypeReferenceNotFound(typeKey, referencedFrom)
    }
  }
  const assertFieldType = (
    fieldType: MessageFieldType | 'plain',
    referencedFrom: string
  ): void => {
    if (typeof fieldType === 'string') {
      return
    }
    if ('type' in fieldType) {
      assertExists(fieldType.type, referencedFrom)
    } else if ('array' in fieldType) {
      assertFieldType(fieldType.array, referencedFrom)
    } else if ('set' in fieldType) {
      assertFieldType(fieldType.set, referencedFrom)
    } else if ('map' in fieldType) {
      assertFieldType(fieldType.map, referencedFrom)
    } else {
      assertFieldType(fieldType.record, referencedFrom)
    }
  }

  for (const [name, typeKey] of Object.entries(messageTypes.messages)) {
    assertExists(typeKey, name)
  }
  for (const [typeKey, definition] of Object.entries(messageTypes.types)) {
    for (const [field, fieldType] of Object.entries(definition.fields)) {
      assertFieldType(fieldType, `${typeKey}.${field}`)
    }
  }
}

/**
 * Registers the message types of a message library, so the bus' default serializer restores them.
 * The file generated by `bus generate-message-types` calls this when it's imported, so you don't need
 * to call it yourself.
 *
 * Registering the same message types again is a no-op, and registering ones with the same `source`
 * replaces them, e.g. when a module is reloaded.
 * @param messageTypes the message types to register
 * @throws MessageTypeReferenceNotFound if the message types refer to a type they don't define
 * @throws MessageTypesConflict if they define a `$name` or type key differently to message types
 * that are already registered. Nothing is registered then.
 */
export const registerMessageTypes = (messageTypes: MessageTypes): void => {
  const registry = getRegistry()
  if (registry.registrations.includes(messageTypes)) {
    return
  }
  assertReferencesExist(messageTypes)
  const registrations = [
    ...registry.registrations.filter(
      registered =>
        messageTypes.source === undefined ||
        registered.source !== messageTypes.source
    ),
    messageTypes
  ]
  registry.merged = merge(registrations)
  registry.registrations = registrations
}

/**
 * Gets every registered message type, merged. A custom serializer can use this to restore types the
 * same way the default serializer does.
 * @returns the merged message types. Don't change them.
 */
export const getMessageTypes = (): MessageTypes => getRegistry().merged
