// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { ChargeCreditCard } from './charge-credit-card.js'
import { FulfilmentState } from './fulfilment-state.js'
import { OrderPlaced } from './order-placed.js'
import { ShippingState } from './shipping-state.js'

// Pass to the bus with Bus.configure().withMessageTypes(messageTypes)
export const messageTypes: MessageTypes = {
  source: '@node-ts/bus-nestjs/src/test/message-types.generated',
  messages: {
    '@node-ts/bus-nestjs/charge-credit-card':
      '@node-ts/bus-nestjs/src/test/charge-credit-card#ChargeCreditCard',
    '@node-ts/bus-nestjs/fulfilment-state':
      '@node-ts/bus-nestjs/src/test/fulfilment-state#FulfilmentState',
    '@node-ts/bus-nestjs/order-placed':
      '@node-ts/bus-nestjs/src/test/order-placed#OrderPlaced',
    '@node-ts/bus-nestjs/shipping-state':
      '@node-ts/bus-nestjs/src/test/shipping-state#ShippingState'
  },
  types: {
    '@node-ts/bus-nestjs/src/test/charge-credit-card#ChargeCreditCard': {
      class: ChargeCreditCard,
      fields: {}
    },
    '@node-ts/bus-nestjs/src/test/fulfilment-state#FulfilmentState': {
      class: FulfilmentState,
      fields: {}
    },
    '@node-ts/bus-nestjs/src/test/order-placed#OrderPlaced': {
      class: OrderPlaced,
      fields: {}
    },
    '@node-ts/bus-nestjs/src/test/shipping-state#ShippingState': {
      class: ShippingState,
      fields: {}
    }
  }
}
