// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { AttributeRoundTripCommand } from './attribute-round-trip-command.js'

// Pass to the bus with Bus.configure().withMessageTypes(messageTypes)
export const messageTypes: MessageTypes = {
  source: '@node-ts/bus-sqs/src/test/message-types.generated',
  messages: {
    '@node-ts/bus-sqs/attribute-round-trip-command':
      '@node-ts/bus-sqs/src/test/attribute-round-trip-command#AttributeRoundTripCommand'
  },
  types: {
    '@node-ts/bus-sqs/src/test/attribute-round-trip-command#AttributeRoundTripCommand':
      {
        class: AttributeRoundTripCommand,
        fields: {}
      }
  }
}
