// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { TestCommand } from './test-command.js'
import { TestRetryCommand } from './test-retry-command.js'

// Pass to the bus with Bus.configure().withMessageTypes(messageTypes)
export const messageTypes: MessageTypes = {
  source: '@node-ts/bus-rabbitmq/src/test/message-types.generated',
  messages: {
    '@node-ts/bus-rabbitmq/test-command':
      '@node-ts/bus-rabbitmq/src/test/test-command#TestCommand',
    '@node-ts/bus-rabbitmq/test-retry-command':
      '@node-ts/bus-rabbitmq/src/test/test-retry-command#TestRetryCommand'
  },
  types: {
    '@node-ts/bus-rabbitmq/src/test/test-command#TestCommand': {
      class: TestCommand,
      fields: {}
    },
    '@node-ts/bus-rabbitmq/src/test/test-retry-command#TestRetryCommand': {
      class: TestRetryCommand,
      fields: {}
    }
  }
}
