// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { TestAddress } from './test-address.js'
import { TestBigIntCommand } from './test-big-int-command.js'
import { TestCommand } from './test-command.js'
import { TestContinueRoundTripWorkflow } from './test-continue-round-trip-workflow.js'
import { TestCustomer } from './test-customer.js'
import { TestEvent } from './test-event.js'
import { TestFailMessage } from './test-fail-message.js'
import { TestGeoPoint } from './test-geo-point.js'
import { TestOrderLine } from './test-order-line.js'
import { TestPoisonedMessage } from './test-poisoned-message.js'
import { TestRoundTripCommand } from './test-round-trip-command.js'
import { TestRoundTripWorkflowState } from './test-round-trip-workflow-state.js'
import { TestStartRoundTripWorkflow } from './test-start-round-trip-workflow.js'

// Pass to the bus with Bus.configure().withMessageTypes(messageTypes)
export const messageTypes: MessageTypes = {
  source: '@node-ts/bus-test/src/helpers/message-types.generated',
  messages: {
    '@node-ts/bus-core/test-command':
      '@node-ts/bus-test/src/helpers/test-command#TestCommand',
    '@node-ts/bus-core/test-event':
      '@node-ts/bus-test/src/helpers/test-event#TestEvent',
    '@node-ts/bus-sqs/test-fail-message':
      '@node-ts/bus-test/src/helpers/test-fail-message#TestFailMessage',
    '@node-ts/bus-test/test-big-int-command':
      '@node-ts/bus-test/src/helpers/test-big-int-command#TestBigIntCommand',
    '@node-ts/bus-test/test-continue-round-trip-workflow':
      '@node-ts/bus-test/src/helpers/test-continue-round-trip-workflow#TestContinueRoundTripWorkflow',
    '@node-ts/bus-test/test-poisoned-message':
      '@node-ts/bus-test/src/helpers/test-poisoned-message#TestPoisonedMessage',
    '@node-ts/bus-test/test-round-trip-command':
      '@node-ts/bus-test/src/helpers/test-round-trip-command#TestRoundTripCommand',
    '@node-ts/bus-test/test-round-trip-workflow-state':
      '@node-ts/bus-test/src/helpers/test-round-trip-workflow-state#TestRoundTripWorkflowState',
    '@node-ts/bus-test/test-start-round-trip-workflow':
      '@node-ts/bus-test/src/helpers/test-start-round-trip-workflow#TestStartRoundTripWorkflow'
  },
  types: {
    '@node-ts/bus-test/src/helpers/test-address#TestAddress': {
      class: TestAddress,
      fields: {
        location: {
          type: '@node-ts/bus-test/src/helpers/test-geo-point#TestGeoPoint'
        }
      }
    },
    '@node-ts/bus-test/src/helpers/test-big-int-command#TestBigIntCommand': {
      class: TestBigIntCommand,
      fields: {
        amount: 'BigInt'
      }
    },
    '@node-ts/bus-test/src/helpers/test-command#TestCommand': {
      class: TestCommand,
      fields: {
        date: 'Date'
      }
    },
    '@node-ts/bus-test/src/helpers/test-continue-round-trip-workflow#TestContinueRoundTripWorkflow':
      {
        class: TestContinueRoundTripWorkflow,
        fields: {}
      },
    '@node-ts/bus-test/src/helpers/test-customer#TestCustomer': {
      class: TestCustomer,
      fields: {
        address: {
          type: '@node-ts/bus-test/src/helpers/test-address#TestAddress'
        },
        previousAddresses: {
          array: {
            type: '@node-ts/bus-test/src/helpers/test-address#TestAddress'
          }
        },
        joinedAt: 'Date'
      }
    },
    '@node-ts/bus-test/src/helpers/test-event#TestEvent': {
      class: TestEvent,
      fields: {}
    },
    '@node-ts/bus-test/src/helpers/test-fail-message#TestFailMessage': {
      class: TestFailMessage,
      fields: {}
    },
    '@node-ts/bus-test/src/helpers/test-geo-point#TestGeoPoint': {
      class: TestGeoPoint,
      fields: {
        surveyedAt: 'Date'
      }
    },
    '@node-ts/bus-test/src/helpers/test-order-line#TestOrderLine': {
      class: TestOrderLine,
      fields: {
        addedAt: 'Date'
      }
    },
    '@node-ts/bus-test/src/helpers/test-poisoned-message#TestPoisonedMessage': {
      class: TestPoisonedMessage,
      fields: {}
    },
    '@node-ts/bus-test/src/helpers/test-round-trip-command#TestRoundTripCommand':
      {
        class: TestRoundTripCommand,
        fields: {
          placedAt: 'Date',
          customer: {
            type: '@node-ts/bus-test/src/helpers/test-customer#TestCustomer'
          },
          lines: {
            array: {
              type: '@node-ts/bus-test/src/helpers/test-order-line#TestOrderLine'
            }
          },
          reminders: { array: 'Date' },
          linesBySku: {
            map: {
              type: '@node-ts/bus-test/src/helpers/test-order-line#TestOrderLine'
            }
          },
          tags: { set: 'plain' },
          shippedAt: 'Date',
          deliveredAt: 'Date',
          billingAddress: {
            type: '@node-ts/bus-test/src/helpers/test-address#TestAddress'
          },
          cancelledAt: 'Date',
          referrer: {
            type: '@node-ts/bus-test/src/helpers/test-customer#TestCustomer'
          },
          untypedDate: 'Date'
        }
      },
    '@node-ts/bus-test/src/helpers/test-round-trip-workflow-state#TestRoundTripWorkflowState':
      {
        class: TestRoundTripWorkflowState,
        fields: {
          startedAt: 'Date',
          customer: {
            type: '@node-ts/bus-test/src/helpers/test-customer#TestCustomer'
          },
          checkpoints: { array: 'Date' }
        }
      },
    '@node-ts/bus-test/src/helpers/test-start-round-trip-workflow#TestStartRoundTripWorkflow':
      {
        class: TestStartRoundTripWorkflow,
        fields: {
          startedAt: 'Date',
          customer: {
            type: '@node-ts/bus-test/src/helpers/test-customer#TestCustomer'
          }
        }
      }
  }
}
