import { MessageTypes } from '@node-ts/bus-messages'

/**
 * Builds message types for test fixtures whose fields need nothing restored, in place of a file generated by
 * `bus generate-message-types`, which bus-core can't depend on
 * @param declarations message classes, definitions or workflow state classes with a static `NAME`, or `$name`s
 * @returns message types with an entry for each of them
 */
export const messageTypesFor = (
  ...declarations: ({ NAME: string } | string)[]
): MessageTypes => {
  const names = declarations.map(declaration =>
    typeof declaration === 'string' ? declaration : declaration.NAME
  )
  return {
    messages: Object.fromEntries(names.map(name => [name, name])),
    types: Object.fromEntries(names.map(name => [name, { fields: {} }]))
  }
}
