// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { TestAddress } from './helpers/test-address.js'
import { TestBigIntCommand } from './helpers/test-big-int-command.js'
import { TestCommand } from './helpers/test-command.js'
import { TestContinueRoundTripWorkflow } from './helpers/test-continue-round-trip-workflow.js'
import { TestCustomer } from './helpers/test-customer.js'
import { TestEvent } from './helpers/test-event.js'
import { TestFailMessage } from './helpers/test-fail-message.js'
import { TestGeoPoint } from './helpers/test-geo-point.js'
import { TestOrderLine } from './helpers/test-order-line.js'
import { TestPoisonedMessage } from './helpers/test-poisoned-message.js'
import { TestRoundTripCommand } from './helpers/test-round-trip-command.js'
import { TestRoundTripWorkflowState } from './helpers/test-round-trip-workflow-state.js'
import { TestStartRoundTripWorkflow } from './helpers/test-start-round-trip-workflow.js'

export const messageTypes: MessageTypes = {
  messages: {
    '@node-ts/bus-core/test-command': 'TestCommand',
    '@node-ts/bus-core/test-event': 'TestEvent',
    '@node-ts/bus-sqs/test-fail-message': 'TestFailMessage',
    '@node-ts/bus-test/test-big-int-command': 'TestBigIntCommand',
    '@node-ts/bus-test/test-continue-round-trip-workflow':
      'TestContinueRoundTripWorkflow',
    '@node-ts/bus-test/test-poisoned-message': 'TestPoisonedMessage',
    '@node-ts/bus-test/test-round-trip-command': 'TestRoundTripCommand',
    '@node-ts/bus-test/test-round-trip-workflow-state':
      'TestRoundTripWorkflowState',
    '@node-ts/bus-test/test-start-round-trip-workflow':
      'TestStartRoundTripWorkflow'
  },
  types: {
    TestAddress: {
      class: TestAddress,
      fields: {
        location: { type: 'TestGeoPoint' }
      }
    },
    TestBigIntCommand: {
      class: TestBigIntCommand,
      fields: {
        amount: 'BigInt'
      }
    },
    TestCommand: {
      class: TestCommand,
      fields: {
        date: 'Date'
      }
    },
    TestContinueRoundTripWorkflow: {
      class: TestContinueRoundTripWorkflow,
      fields: {}
    },
    TestCustomer: {
      class: TestCustomer,
      fields: {
        address: { type: 'TestAddress' },
        previousAddresses: { array: { type: 'TestAddress' } },
        joinedAt: 'Date'
      }
    },
    TestEvent: {
      class: TestEvent,
      fields: {}
    },
    TestFailMessage: {
      class: TestFailMessage,
      fields: {}
    },
    TestGeoPoint: {
      class: TestGeoPoint,
      fields: {
        surveyedAt: 'Date'
      }
    },
    TestOrderLine: {
      class: TestOrderLine,
      fields: {
        addedAt: 'Date'
      }
    },
    TestPoisonedMessage: {
      class: TestPoisonedMessage,
      fields: {}
    },
    TestRoundTripCommand: {
      class: TestRoundTripCommand,
      fields: {
        placedAt: 'Date',
        customer: { type: 'TestCustomer' },
        lines: { array: { type: 'TestOrderLine' } },
        reminders: { array: 'Date' },
        linesBySku: { map: { type: 'TestOrderLine' } },
        tags: { set: 'plain' },
        shippedAt: 'Date',
        deliveredAt: 'Date',
        billingAddress: { type: 'TestAddress' },
        cancelledAt: 'Date',
        referrer: { type: 'TestCustomer' },
        untypedDate: 'Date'
      }
    },
    TestRoundTripWorkflowState: {
      class: TestRoundTripWorkflowState,
      fields: {
        startedAt: 'Date',
        customer: { type: 'TestCustomer' },
        checkpoints: { array: 'Date' }
      }
    },
    TestStartRoundTripWorkflow: {
      class: TestStartRoundTripWorkflow,
      fields: {
        startedAt: 'Date',
        customer: { type: 'TestCustomer' }
      }
    }
  }
}
