// Generated by `bus generate-message-types` from '@node-ts/bus-cli'. Don't edit it by hand.
import type { MessageTypes } from '@node-ts/bus-messages'
import { registerMessageTypes } from '@node-ts/bus-messages'
import { RunTask } from './run-task.js'
import { TaskRan } from './task-ran.js'
import { TestCommand } from './test-command.js'
import { TestWorkflowState } from './test-workflow-state.js'

export const messageTypes: MessageTypes = {
  source: '@node-ts/bus-mongodb/test/message-types.generated',
  messages: {
    '@node-ts/bus-mongodb/run-task':
      '@node-ts/bus-mongodb/test/run-task#RunTask',
    '@node-ts/bus-mongodb/task-ran':
      '@node-ts/bus-mongodb/test/task-ran#TaskRan',
    '@node-ts/bus-mongodb/test-command':
      '@node-ts/bus-mongodb/test/test-command#TestCommand',
    TestWorkflowState:
      '@node-ts/bus-mongodb/test/test-workflow-state#TestWorkflowState'
  },
  types: {
    '@node-ts/bus-mongodb/test/run-task#RunTask': {
      class: RunTask,
      fields: {}
    },
    '@node-ts/bus-mongodb/test/task-ran#TaskRan': {
      class: TaskRan,
      fields: {}
    },
    '@node-ts/bus-mongodb/test/test-command#TestCommand': {
      class: TestCommand,
      fields: {}
    },
    '@node-ts/bus-mongodb/test/test-workflow-state#TestWorkflowState': {
      class: TestWorkflowState,
      fields: {}
    }
  }
}

// Registers the types with the bus as soon as this file is imported
registerMessageTypes(messageTypes)
